# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: unless-stopped
#     ports:
#       - "8080:80"


# version: "3.8"

# services:
#   gitlab-runner:
#     image: gitlab/gitlab-runner:alpine
#     container_name: gitlab-runner
#     restart: always
#     volumes:
#       - ./gitlab-runner/config:/etc/gitlab-runner
#       - /var/run/docker.sock:/var/run/docker.sock
